// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgressSoft.Apolo.Infrastructure;

#nullable disable

namespace ProgressSoft.Apolo.Infrastructure.Migrations
{
    [DbContext(typeof(ApoloDbContext))]
    [Migration("20241014090336_ModifyImageMigration")]
    partial class ModifyImageMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProgressSoft.Apolo.Domain.BusinessCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnOrder(6);

                    b.Property<DateOnly>("BirthOfDate")
                        .HasColumnType("date")
                        .HasColumnOrder(3);

                    b.Property<string>("Email")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(320)")
                        .HasColumnOrder(4);

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint")
                        .HasColumnOrder(2);

                    b.Property<int?>("ImageId")
                        .HasColumnType("int")
                        .HasColumnOrder(7);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnOrder(1);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnOrder(5);

                    b.HasKey("Id")
                        .HasName("PrimaryKey_BusinessCards");

                    b.HasIndex("ImageId");

                    b.HasIndex(new[] { "Email" }, "Unique_BusinessCard_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "Name" }, "Unique_BusinessCard_Name")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "Unique_BusinessCard_Phone")
                        .IsUnique();

                    b.ToTable("BusinessCards", "dbo");
                });

            modelBuilder.Entity("ProgressSoft.Apolo.Domain.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("EncodedImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnOrder(1);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnOrder(2);

                    b.HasKey("Id")
                        .HasName("PrimaryKey_Images");

                    b.ToTable("Images", "asset");
                });

            modelBuilder.Entity("ProgressSoft.Apolo.Domain.BusinessCard", b =>
                {
                    b.HasOne("ProgressSoft.Apolo.Domain.Image", "Image")
                        .WithMany("BusinessCards")
                        .HasForeignKey("ImageId")
                        .HasConstraintName("FK_Image_BusinessCard");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("ProgressSoft.Apolo.Domain.Image", b =>
                {
                    b.Navigation("BusinessCards");
                });
#pragma warning restore 612, 618
        }
    }
}
